### ISSUE TITLE
Consider changing the name of the incubation effort repo

### ISSUE THREAD

**Issue by cookiecrook** [WICG/aria-virtualcontent#2]
Can we change the name of the repo to something more agnostic, like “accessible loading or searching of content”? Leaving the repo titled with the proposed solution limits the flexibility of an incubation effort. Even if we all agreed on a declarative approach, there were specific concerns with the term "virtual" as people though it might be related to virtual reality (VR) interfaces, or associated with the AOM effort to load a virtual accessibility tree for HTML `<canvas>` or other custom views.

In addition to the proposed declarative approach (specifically “aria-virtualcontent” or other ones we discussed), there was chatter that this might be solved a number of other ways. For example, common AT actions (like jump to next heading) could be mapped to web-app-specific commands (opt-h?). There are probably a number of other ways to solve these problems, including new JavaScript API.

**Comment by atanassov** [comment]
More than happy to. Renamed to accessible-loading-and-searching-of-content

**Comment by cookiecrook** [comment]
Thanks for the quick turnaround!
